spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: arbutuslake
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /swagger.html